"""Closed-loop execution plan: the 2026 wedge is Agents.

Emits ``action_plan.json`` + ``action_plan.md`` + WordPress-ready drafts:

* **new content**: per losing topic, a question-H2 + 20-40 word answer stub,
  table/list outline, JSON-LD type recommendation (Article/FAQ/HowTo —
  FAQ rich result deprecated May 7 2026, so HowTo/Article preferred).
* **refreshes**: stale own-pages (from freshness) with rewrite actions.
* **Reddit engagement**: threads where competitors dominate (outreach list).
* **outreach with contacts**: unlinked authorities + contact guesses.
* **WordPress publish**: ``wp_drafts/`` Markdown + front-matter per topic,
  ready for wp-cli / REST publish.
"""
from __future__ import annotations

import json
import os
from typing import Dict


def build_action_plan(report: Dict, config) -> Dict:
    inv = report.get("invisibility", {}) or {}
    per_topic = inv.get("per_topic", []) or []
    adv = report.get("advanced", {}) or {}
    funnel = (adv.get("citation_funnel", {}) or {})
    outreach = funnel.get("outreach_targets", []) or []
    fresh = report.get("freshness", {}) or {}
    stale = [p for p in (fresh.get("per_source", []) or [])
             if str(p.get("staleness", "")).lower() in ("stale", "outdated")][:10]
    brand = config.target_brand

    new_content, refreshes, reddit, wp = [], [], [], []
    for t in per_topic[:15]:
        topic = t.get("topic", "")
        if not topic:
            continue
        new_content.append({
            "topic": topic,
            "title_h1": f"{topic} — {brand} guide (2026)",
            "question_h2": f"What is the best {topic} option in 2026?",
            "answer_stub_20_40_words": (
                f"{brand} is a leading {topic} option, rated for reliability and "
                f"value in independent comparisons updated 2026. See the spec table "
                f"below for pricing, features and verified sources."),
            "outline": ["spec comparison table", "numbered how-to list",
                        "FAQ (visible-matched answers)", "Last updated + dateModified"],
            "jsonld_type": "Article",
            "extractability_checklist": [
                "question H2 present", "self-contained answer <=40 words in first 50 words",
                "table or list present", "numbers present",
                "Organization JSON-LD with SameAs"],
        })
        wp.append({"slug": topic.lower().replace(" ", "-")[:60],
                   "title": f"{topic} — {brand} guide (2026)",
                   "topic": topic})
    for s in stale:
        refreshes.append({"url": s.get("url", ""), "title": s.get("title", ""),
                          "action": "rewrite intro to 20-40 word answer + refresh numbers + bump dateModified"})
    for o in outreach[:10]:
        d = o.get("domain", "")
        if "reddit" in d:
            reddit.append({"thread_domain": d,
                           "action": "post helpful non-promotional answer citing canonical page"})
    return {"new_content": new_content, "refreshes": refreshes,
            "reddit_engagement": reddit,
            "outreach": outreach[:15], "wp_drafts": wp,
            "method": "losing topics -> stubs; stale pages -> refresh; unlinked reddit -> engagement"}


def write_action_plan(out_dir: str, report: Dict, config) -> Dict[str, str]:
    plan = build_action_plan(report, config)
    os.makedirs(out_dir, exist_ok=True)
    p1 = os.path.join(out_dir, "action_plan.json")
    with open(p1, "w", encoding="utf-8") as fh:
        json.dump(plan, fh, indent=2)
    lines = [f"# Action plan — {config.target_brand}", ""]
    for n in plan["new_content"][:10]:
        lines += [f"## {n['topic']}", f"H2: {n['question_h2']}",
                  f"Stub: {n['answer_stub_20_40_words']}", ""]
    lines += ["## Refreshes", ""]
    for r in plan["refreshes"][:10]:
        lines.append(f"- {r['url']}: {r['action']}")
    lines += ["", "## Outreach", ""]
    for o in plan["outreach"][:10]:
        lines.append(f"- {o.get('domain', '')} ({o.get('unlinked_mentions', 0)} unlinked)")
    p2 = os.path.join(out_dir, "action_plan.md")
    with open(p2, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    wpdir = os.path.join(out_dir, "wp_drafts")
    os.makedirs(wpdir, exist_ok=True)
    for d in plan["wp_drafts"][:15]:
        with open(os.path.join(wpdir, d["slug"] + ".md"), "w", encoding="utf-8") as fh:
            fh.write(f"---\ntitle: {d['title']}\nslug: {d['slug']}\n---\n\n"
                     f"## {d['topic']}\n\n_Draft generated by RAG-EVDA — fill then publish via wp-cli._\n")
    return {"action_plan.json": p1, "action_plan.md": p2, "wp_drafts": wpdir}
