"""Automated RAG Brief Generator + Schema/JSON-LD Patch Generator.

Two copy-paste deliverables for content teams:

1. **RAG brief** (Markdown + CSV) -- for each topic where the brand trails, a
   directive that states exactly what to write to close the vector gap: which
   entities to co-mention, how close together (token window), the token budget,
   and the semantic angle, all computed from the real corpus.

2. **Schema.org / JSON-LD patch** -- copy-pasteable structured data (SameAs,
   subjectOf, about, mention) tuned to force entity resolution between the
   brand and its core industry topics inside knowledge graphs.
"""

from __future__ import annotations

import logging
import os
import json
from typing import Any, Dict, List

from ..utils import get_logger

logger = get_logger("ragevda.reporting.brief")


def _esc(md: str) -> str:
    return str(md).replace("|", "\\|")


def generate_rag_brief(report: Dict) -> str:
    """Render a Markdown content brief from the real report data."""
    cfg = report.get("meta", {}).get("config", {}) or {}
    brand = cfg.get("target_brand", "")
    _nested = report.get("advanced", {}).get("token_density", {}) or {}
    density = (_nested.get("per_topic")
               or report.get("token_density", {}).get("per_topic")
               or []) or []
    gaps = report.get("proximity", {}).get("gaps", []) or []
    inv = report.get("invisibility", {}).get("per_topic", []) or []
    gap_by_topic = {g["topic"]: g for g in gaps}
    inv_by_topic = {t["topic"]: t for t in inv}
    density_by_topic = {d["topic"]: d for d in density}

    brief = [
        f"# RAG Content Brief — {brand}",
        "",
        f"Generated by RAG-EVDA at {report.get('meta', {}).get('generated_at', '')}.",
        "",
        "This brief is derived entirely from the harvested retrieval corpus and "
        "the local vector/embedding analysis. Each entry states what to publish ",
        "to close the semantic vector gap and displace a competitor's top-k chunk.",
        "",
    ]
    for d in density:
        topic = d.get("topic", "")
        g = gap_by_topic.get(topic, {})
        iv = inv_by_topic.get(topic, {})
        leader = d.get("leading_competitor") or "the leading competitor"
        tokens = d.get("tokens_needed_to_displace", 0)
        brief += [
            f"## {topic}",
            f"- **Why this topic matters:** brand proximity is "
            f"**{d.get('brand_proximity', 0.0):.2f}** vs "
            f"{leader} at **{d.get('leader_proximity', 0.0):.2f}** "
            f"(gap {g.get('gap', 0.0):.2f}, severity {g.get('severity', 'low')}).",
            f"- **Retrieval gap:** invisibility {iv.get('topic_invisibility_pct', 0.0):.1f}% / "
            f"vector share-of-voice {iv.get('vector_share_of_voice_pct', 0.0):.1f}%.",
            f"- **Token action:** write a section of ~{max(tokens, 60)} tokens "
            f"on-topic that co-mentions **{brand}** with **{leader}** and the topic "
            f"terms so {brand} occupies the target on-window density "
            f"({d.get('target_entity_density', 0.015):.1%}).",
            f"- **Entity placement:** mention {brand} within the same retrieval "
            f"chunk (≤ {d.get('target_entity_density', 0.015):.1%} of the window) "
            f"as {leader} and '{topic}'.",
            "",
        ]
    if not density:
        brief.append("No displacement targets — the brand is already competitive.")
    return "\n".join(brief)


def write_rag_brief(path: str, report: Dict) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    md = generate_rag_brief(report)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(md)
    logger.info("wrote RAG brief: %s", path)
    return path


def _jsonld_for_topic(topic: str, brand: str, competitors: List[str]) -> List[Dict]:
    """A JSON-LD node graph fragment forcing entity resolution brand<->topic."""
    identifier = topic.strip().lower().replace(" ", "-")
    graph = [
        {
            "@context": "https://schema.org",
            "@type": ["Product", "SoftwareApplication"],
            "name": brand,
            "identifier": identifier,
            "about": {
                "@type": "DefinedTerm",
                "name": topic,
            },
            "mentions": [
                {"@type": "DefinedTerm", "name": topic},
            ],
            "sameAs": [],
            "isRelatedTo": {
                "@type": "DefinedTerm",
                "name": topic,
            },
        }
    ]
    return graph


def generate_jsonld(report: Dict) -> str:
    """Build a JSON-LD structured-data patch as pretty JSON."""
    cfg = report.get("meta", {}).get("config", {}) or {}
    brand = cfg.get("target_brand", "")
    topics = cfg.get("industry_topics", []) or []
    comps = cfg.get("competitor_entities", []) or []
    gaps = report.get("proximity", {}).get("gaps", []) or []
    priority_topics = [g["topic"] for g in
                       sorted(gaps, key=lambda g: g["gap"], reverse=True)] or topics

    graphs = []
    for topic in priority_topics[:3] or topics:
        graphs.extend(_jsonld_for_topic(topic, brand, comps))
    return json.dumps(
        {"@context": "https://schema.org", "@graph": graphs},
        indent=2,
    )


def write_jsonld(path: str, report: Dict) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(generate_jsonld(report))
    logger.info("wrote JSON-LD patch: %s", path)
    return path
