"""Automated RAG Brief Generator + Schema/JSON-LD Patch Generator.

Two copy-paste deliverables for content teams:

1. **RAG brief** (Markdown + CSV) -- for each topic where the brand trails, a
   directive that states exactly what to write to close the vector gap: which
   entities to co-mention, how close together (token window), the token budget,
   and the semantic angle, all computed from the real corpus.

2. **Schema.org / JSON-LD patch** -- copy-pasteable structured data (SameAs,
   subjectOf, about, mention) tuned to force entity resolution between the
   brand and its core industry topics inside knowledge graphs.
"""

from __future__ import annotations

import logging
import os
import json
from typing import Any, Dict, List

from ..utils import get_logger

logger = get_logger("ragevda.reporting.brief")


def _esc(md: str) -> str:
    return str(md).replace("|", "\\|")


def generate_rag_brief(report: Dict) -> str:
    """Render a Markdown content brief from the real report data."""
    cfg = report.get("meta", {}).get("config", {}) or {}
    brand = cfg.get("target_brand", "")
    _nested = report.get("advanced", {}).get("token_density", {}) or {}
    density = (_nested.get("per_topic")
               or report.get("token_density", {}).get("per_topic")
               or []) or []
    gaps = report.get("proximity", {}).get("gaps", []) or []
    inv = report.get("invisibility", {}).get("per_topic", []) or []
    prox_rows = report.get("proximity", {}).get("rows", []) or []
    syn = report.get("advanced", {}).get("synthetic_queries", {}).get("per_entity", {}) or {}
    gap_by_topic = {g["topic"]: g for g in gaps}
    inv_by_topic = {t["topic"]: t for t in inv}
    density_by_topic = {d["topic"]: d for d in density}
    prox_by_entity_topic = {(r["entity"], r["topic"]): r for r in prox_rows}

    brief = [
        f"# RAG Content Brief — {brand}",
        "",
        f"Generated by RAG-EVDA at {report.get('meta', {}).get('generated_at', '')}.",
        "",
        "This brief is derived entirely from the harvested retrieval corpus and "
        "the local vector/embedding analysis. Each entry states what to publish ",
        "to close the semantic vector gap and displace a competitor's top-k chunk.",
        "",
        "## Priority summary",
        "",
    ]
    # Overall priority map (severity -> recommended action) up front.
    sev_order = {"critical": 0, "high": 1, "low": 2}
    prioritized = sorted(density, key=lambda d: sev_order.get(d.get("severity", "low"), 3))
    for i, d in enumerate(prioritized, 1):
        topic = d.get("topic", "")
        leader = d.get("leading_competitor") or "the leading competitor"
        tokens = d.get("tokens_needed_to_displace", 0)
        brief.append(
            f"{i}. **[{d.get('severity', 'low').upper()}] {topic}** — "
            f"~{max(tokens, 0)} tokens (top-{cfg.get('top_k_retrieval', 5)} "
            f"retrieval) vs {leader}."
        )

    brief += ["", "---", ""]

    for d in prioritized:
        topic = d.get("topic", "")
        g = gap_by_topic.get(topic, {})
        iv = inv_by_topic.get(topic, {})
        leader = d.get("leading_competitor") or "the leading competitor"
        tokens = d.get("tokens_needed_to_displace", 0)
        # synthetic queries the team can target directly
        entity_queries = syn.get(brand, [])
        q_lines = "\n".join(
            f"  - *{q.get('query', '')}* (confidence "
            f"{q.get('retrieval_confidence', 0.0):.2f})"
            for q in entity_queries if q.get("topic") == topic
        ) or "  - (none targeted at this topic yet)"
        brand_row = prox_by_entity_topic.get((brand, topic), {})
        leader_row = prox_by_entity_topic.get((leader, topic), {})
        brief += [
            f"## {topic}",
            "",
            f"**Severity:** {d.get('severity', 'low').upper()} — "
            f"density gap ratio {d.get('density_gap_ratio', 'n/a')}.",
            "",
            f"**Why this topic matters:** brand proximity is "
            f"**{d.get('brand_proximity', 0.0):.2f}** vs "
            f"{leader} at **{d.get('leader_proximity', 0.0):.2f}** "
            f"(gap {g.get('gap', 0.0):.2f}, severity {g.get('severity', 'low')}).",
            f"- Brand within-window usage: {d.get('brand_on_window_usage_tokens', 0)} "
            f"tokens; {leader} at {d.get('leader_on_window_usage_tokens', 0)} tokens.",
            f"- Retrieval window token base this topic: "
            f"{d.get('retrieval_window_token_base', 0):,} (real BPE windows).",
            f"- Brand density {d.get('brand_density', 0.0):.1%} vs leader "
            f"{d.get('leader_density', 0.0):.1%}.",
            "",
            f"**Retrieval gap:** invisibility {iv.get('topic_invisibility_pct', 0.0):.1f}% / "
            f"vector share-of-voice {iv.get('vector_share_of_voice_pct', 0.0):.1f}%.",
            "",
            f"**Token action:** write a section of ~{max(tokens, 60)} tokens "
            f"on-topic that co-mentions **{brand}** with **{leader}** and the topic "
            f"terms so {brand} occupies the target on-window density "
            f"({d.get('target_entity_density', 0.015):.1%}).",
            f"- **Entity placement:** mention {brand} within the same retrieval "
            f"chunk (≤ {d.get('target_entity_density', 0.015):.1%} of the window) "
            f"as {leader} and '{topic}'.",
            "",
            f"**Target synthetic queries (reverse-engineered for {topic}):**",
            q_lines,
            "",
            "---",
            "",
        ]
    if not density:
        brief.append("No displacement targets — the brand is already competitive.")
    # ---- Executive visibility + closed-loop appendix (2026 depth) ----
    adv = report.get("advanced", {}) or {}
    vis = adv.get("visibility", {}) or {}
    if vis.get("table"):
        brief += ["", "## Executive visibility (C-suite translation)", ""]
        for r in vis["table"]:
            brief.append(
                f"- **{r.get('entity', '')}**: Visibility {r.get('visibility', 0)}/100 "
                f"(Position #{r.get('position', '?')}) · mentions {r.get('mentions', 0)} "
                f"vs linked citations {r.get('citations_linked', 0)} "
                f"(unlinked {r.get('citations_unlinked', 0)}).")
        brief.append(
            f"\nCompetitor median visibility {vis.get('competitor_median_visibility', 0)}; "
            f"brand delta {vis.get('delta_vs_median', 0):+} (Semrush-style).")
    funnel = adv.get("citation_funnel", {}) or {}
    if funnel.get("funnel"):
        brief += ["", "## Cited-vs-found funnel + outreach", ""]
        for f in funnel["funnel"]:
            brief.append(
                f"- **{f.get('entity', '')}**: found {f.get('found_docs', 0)} → "
                f"mentioned {f.get('mention_docs', 0)} ({f.get('mention_rate_pct', 0)}%) → "
                f"cited {f.get('cited_docs', 0)} → linked {f.get('linked_docs', 0)}.")
        for o in (funnel.get("outreach_targets", []) or [])[:8]:
            brief.append(f"- Outreach: {o.get('domain', '')} "
                         f"({o.get('unlinked_mentions', 0)} unlinked) → {o.get('contact_guess', '')}")
    ev = adv.get("eval", {}) or {}
    if ev.get("fixes"):
        brief += ["", "## FactCheck auto-corrections (fix loop, not just fail)", ""]
        for fx in ev["fixes"][:12]:
            brief.append(f"- [{fx.get('type', '')}] {fx.get('evidence', '')[:160]}")
            brief.append(f"  Fix: {fx.get('suggestion', '')[:300]}")
    fo = adv.get("fanout", {}) or {}
    if fo.get("count"):
        brief.append(f"\n## Query fan-out: {fo['count']} volume-weighted prompts "
                     f"(total weight {fo.get('total_weight', 0)}). See report.json advanced.fanout.")
    sm = adv.get("sentiment_matrix", {}) or {}
    if sm.get("word_association"):
        brief += ["", "## Word association (what words own you)", ""]
        for ent, words in list(sm["word_association"].items())[:6]:
            top = ", ".join(w.get("word", "") for w in (words or [])[:8])
            brief.append(f"- **{ent}**: {top}")
    return "\n".join(brief)


def write_rag_brief(path: str, report: Dict) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    md = generate_rag_brief(report)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(md)
    logger.info("wrote RAG brief: %s", path)
    return path


def _jsonld_for_topic(topic: str, brand: str, competitors: List[str]) -> List[Dict]:
    """A JSON-LD node graph fragment forcing entity resolution brand<->topic.

    Real-data version: links the brand to its topic AND to each competitor
    (competitor comparison) with per-topic identifiers, instead of generic
    boilerplate with empty sameAs.
    """
    identifier = topic.strip().lower().replace(" ", "-")
    brand_id = brand.strip().lower().replace(" ", "-")
    mentions = [{"@type": "DefinedTerm", "name": topic}]
    for c in (competitors or [])[:5]:
        mentions.append({"@type": "Organization", "name": c})
    graph = [
        {
            "@context": "https://schema.org",
            "@type": ["Organization"],
            "@id": f"https://example.org/#{brand_id}",
            "name": brand,
            "identifier": f"{brand_id}-{identifier}",
            "about": {
                "@type": "DefinedTerm",
                "name": topic,
            },
            "mentions": mentions,
            "knowsAbout": [{"@type": "DefinedTerm", "name": topic}],
            "isRelatedTo": [{"@type": "Organization", "name": c} for c in (competitors or [])[:5]],
        }
    ]
    return graph


def generate_jsonld(report: Dict) -> str:
    """Build a JSON-LD structured-data patch as pretty JSON."""
    cfg = report.get("meta", {}).get("config", {}) or {}
    brand = cfg.get("target_brand", "")
    topics = cfg.get("industry_topics", []) or []
    comps = cfg.get("competitor_entities", []) or []
    gaps = report.get("proximity", {}).get("gaps", []) or []
    priority_topics = [g["topic"] for g in
                       sorted(gaps, key=lambda g: g["gap"], reverse=True)] or topics

    graphs = []
    for topic in priority_topics[:3] or topics:
        graphs.extend(_jsonld_for_topic(topic, brand, comps))
    return json.dumps(
        {"@context": "https://schema.org", "@graph": graphs},
        indent=2,
    )


def write_jsonld(path: str, report: Dict) -> str:
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(generate_jsonld(report))
    logger.info("wrote JSON-LD patch: %s", path)
    return path
