"""llms.txt + agent.json + MCP manifest generator (P0).

Google (May 15 2026): no ranking boost — still mandatory for Perplexity/ChatGPT
retrieval. Generates from REAL report data (never templated fluff):

* ``llms.txt`` — brand summary, top topics, key URLs, contact/pricing hooks;
* ``llms-full.txt`` — per-topic brief + displacement actions;
* ``agent.json`` — pricing/stock tool endpoints for AI agents;
* ``.well-known/mcp.json`` — MCP server manifest (get_pricing/check_stock).
"""
from __future__ import annotations

import json
import os
from typing import Dict


def build_llms_txt(report: Dict, config) -> str:
    meta = report.get("meta", {})
    brand = config.target_brand
    topics = list(config.industry_topics)
    prov = report.get("provenance", [])[:10]
    recs = report.get("recommendations", [])[:8]
    lines = [f"# {brand}", "",
             f"Generated by RAG-EVDA v{meta.get('version', '')} "
             f"(verification {meta.get('verification_score', 0)}/100).", ""]
    lines += ["## Topics", ""]
    for t in topics:
        lines.append(f"- {t}")
    lines += ["", "## Key sources", ""]
    for p in prov:
        lines.append(f"- [{p.get('title', p.get('url', ''))}]({p.get('url', '')})")
    lines += ["", "## Actions for AI agents", ""]
    for r in recs:
        lines.append(f"- {r.get('title', '')}: {r.get('action', '')}")
    base = (getattr(config, "site_base_url", "") or "").rstrip("/")
    if base:
        lines += ["", f"Base URL: {base}"]
    return "\n".join(lines) + "\n"


def build_llms_full(report: Dict, config) -> str:
    adv = report.get("advanced", {})
    dens = (adv.get("token_density", {}) or {}).get("per_topic", [])
    parts = [build_llms_txt(report, config), "\n## Per-topic displacement\n"]
    for d in dens:
        parts.append(f"\n### {d.get('topic', '')}\n"
                     f"Tokens to displace leader: {d.get('tokens_to_displace', '?')}\n")
    return "\n".join(parts)


def build_agent_json(report: Dict, config) -> Dict:
    base = (getattr(config, "site_base_url", "") or "https://example.com").rstrip("/")
    tools = list(getattr(config, "mcp_tools", ["get_pricing", "check_stock"]) or [])
    return {"name": config.target_brand, "base_url": base,
            "tools": [{"name": t, "endpoint": f"{base}/api/{t}"} for t in tools],
            "verification_score": report.get("meta", {}).get("verification_score", 0)}


def build_mcp_manifest(report: Dict, config) -> Dict:
    agent = build_agent_json(report, config)
    return {"mcp_version": "1.0", "server": config.target_brand,
            "tools": agent["tools"],
            "lighthouse_agentic": "13.3-ready: get_pricing/check_stock exposed"}


def build_webmcp(report: Dict, config) -> Dict:
    """WebMCP manifest (Chrome 149 origin trial, navigator.modelContext).

    Google Search Central (2026): llms.txt has zero ranking/AIO effect —
    keep it lean for Cursor/Claude Code only. The PRIORITY surface is
    /.well-known/webmcp.json + /mcp.json + /agent.json (declarative tools
    -> imperative modelContext calls). This manifest is WebMCP-ready.
    """
    agent = build_agent_json(report, config)
    base = agent.get("base_url", "https://example.com")
    return {
        "webmcp_version": "1.0",
        "site": config.target_brand,
        "base_url": base,
        "contexts": [
            {"name": "catalog", "tools": agent["tools"],
             "declarative": True, "imperative": "navigator.modelContext.callTool"},
        ],
        "endpoints": {
            "webmcp": "/.well-known/webmcp.json",
            "mcp": "/mcp.json",
            "agent": "/agent.json",
            "llms_txt": "/llms.txt",
        },
        "verification_score": report.get("meta", {}).get("verification_score", 0),
        "note": "llms.txt kept lean for coding agents only; WebMCP is the agentic surface",
    }


def write_llms_outputs(out_dir: str, report: Dict, config) -> Dict[str, str]:
    os.makedirs(out_dir, exist_ok=True)
    paths = {}
    llms = build_llms_txt(report, config)
    p1 = os.path.join(out_dir, "llms.txt")
    with open(p1, "w", encoding="utf-8") as fh:
        fh.write(llms)
    paths["llms.txt"] = p1
    p2 = os.path.join(out_dir, "llms-full.txt")
    with open(p2, "w", encoding="utf-8") as fh:
        fh.write(build_llms_full(report, config))
    paths["llms-full.txt"] = p2
    p3 = os.path.join(out_dir, "agent.json")
    with open(p3, "w", encoding="utf-8") as fh:
        json.dump(build_agent_json(report, config), fh, indent=2)
    paths["agent.json"] = p3
    wk = os.path.join(out_dir, ".well-known")
    os.makedirs(wk, exist_ok=True)
    p4 = os.path.join(wk, "mcp.json")
    with open(p4, "w", encoding="utf-8") as fh:
        json.dump(build_mcp_manifest(report, config), fh, indent=2)
    paths["mcp.json"] = p4
    # WebMCP-first (Chrome 149): /.well-known/webmcp.json + /mcp.json + /agent.json
    p5 = os.path.join(wk, "webmcp.json")
    with open(p5, "w", encoding="utf-8") as fh:
        json.dump(build_webmcp(report, config), fh, indent=2)
    paths["webmcp.json"] = p5
    p6 = os.path.join(out_dir, "mcp.json")
    with open(p6, "w", encoding="utf-8") as fh:
        json.dump(build_mcp_manifest(report, config), fh, indent=2)
    paths["mcp-root.json"] = p6
    return paths
